version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:80"
    container_name: vite-react-app
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
